### ISSUE TITLE
nginx tries to bind port 80

### ISSUE THREAD

**Issue by bassista** [Ahwxorg/LibreY#144]
I don't get why I have this error at startup:
nginx: [emerg] socket() [::]:**80** failed (97: Address family not supported by protocol)

I'm using this docker image: ghcr.io/ahwxorg/librey:latest and ipv6 is disabled on the host machine.

If I look at docker/nginx.conf I see that It should bind port 8080 so why do I get this error related to port 80?

Can you add an env variable to have only ipv4 binding, otherwise can you explain to me how I can build the docker image disabling the ipv6 binding? - my best guess was that I had to modify the nginx.con file, but there I found a mismatch between the port stated in this file (8080) and the one bound at server start (80).

Thanks in advance.

**Comment by bassista** [comment]
services:
  librey:
    image: ghcr.io/ahwxorg/librey:latest
    container_name: librey
    environment:	  
      - CONFIG_GOOGLE_DOMAIN=en
      - CONFIG_LANGUAGE=en
      - CONFIG_WIKIPEDIA_LANGUAGE="en"	  
      - CONFIG_NUMBER_OF_RESULTS=100
      - CONFIG_INVIDIOUS_INSTANCE=https://yt.ahwx.org
      - CONFIG_DISABLE_BITTORRENT_SEARCH=false
      - CONFIG_HIDDEN_SERVICE_SEARCH=false
      - CONFIG_INSTANCE_FALLBACK=true
      - CONFIG_RATE_LIMIT_COOLDOWN=25
      - CONFIG_CACHE_TIME=20
      - CONFIG_DISABLE_API=false
      - CONFIG_TEXT_SEARCH_ENGINE=auto
      - CURLOPT_PROXY_ENABLED=false
      - CURLOPT_PROXY=192.0.2.53:8388
      - CURLOPT_PROXYTYPE=CURLPROXY_HTTP
      - CURLOPT_USERAGENT=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:116.0) Gecko/20100101 Firefox/116.0
      - CURLOPT_FOLLOWLOCATION=true
    volumes:
      - ./php_logs:/var/log/php83 
    restart: unless-stopped

**Comment by Ahwxorg** [comment]
> Can you add an env variable to have only ipv4 binding

As far as I am aware, (and after a quick search, it looks like that's still the case) NGINX does not automatically bind to IPv6. I have not implemented IPv6 here either.

It does look like an IP/port related error, so that's weird.

Also: I strongly recommend against letting Docker bind to IPv6, as you are better of doing that on the reverse proxy side, in my opinion.

**Comment by bassista** [comment]
no, that's it. There is no port cause if it will start I will use a reverse proxy to expose it.

**Comment by Ahwxorg** [comment]
Please take a look at how Docker networking works.

**Comment by bassista** [comment]
Using the docker-compose.yml you versioned here gives the same error:

[+] Running 1/1
 ✔ Container librey  Created                                                                                                                                          0.2s
Attaching to librey
librey  | nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
librey exited with code 1

```
services:
  librey:
    image: ghcr.io/ahwxorg/librey:latest
    container_name: librey
    network_mode: bridge
    ports:
      - 8080:8080
    environment:
      - CONFIG_GOOGLE_DOMAIN=com
      - CONFIG_LANGUAGE=en
      - CONFIG_NUMBER_OF_RESULTS=10
      - CONFIG_INVIDIOUS_INSTANCE=https://yt.ahwx.org
      - CONFIG_DISABLE_BITTORRENT_SEARCH=false
      - CONFIG_HIDDEN_SERVICE_SEARCH=false
      - CONFIG_INSTANCE_FALLBACK=true
      - CONFIG_RATE_LIMIT_COOLDOWN=25
      - CONFIG_CACHE_TIME=20
      - CONFIG_DISABLE_API=false
      - CONFIG_TEXT_SEARCH_ENGINE=auto
      - CURLOPT_PROXY_ENABLED=false
      - CURLOPT_PROXY=192.0.2.53:8388
      - CURLOPT_PROXYTYPE=CURLPROXY_HTTP
      - CURLOPT_USERAGENT=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:116.0) Gecko/20100101 Firefox/116.0
      - CURLOPT_FOLLOWLOCATION=true
    volumes:
      # - ./nginx_logs:/var/log/nginx # Disabled by default. These are the NGINX request logs.
      - ./php_logs:/var/log/php83 # Enabled by default. These are the PHP error logs.
    restart: unless-stopped
  watchtower: # Watchtower is not required but highly recommended, since Watchtower will re-pull and restart the LibreY container automatically whenever there's an update.
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```
