### ISSUE TITLE
Searching gives blank page

### ISSUE THREAD

**Issue by impaktor** [Ahwxorg/LibreY#165]
## Intro
I decided to try LibreY as SearchXNG's javascript messes with my ancient [conkeror browser](https://impaktor.gitlab.io/conkeror.html), and startpage.com no longer works in conkeror.

## setup  
used the following docker compose (from website, no changes):
```
services:
  librex:
    image: librex/librex:latest
    container_name: librex
    network_mode: bridge
    ports:
      - 8080:8080
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - TZ="Europe/Copenhagen"
      - CONFIG_GOOGLE_DOMAIN="com"
      - CONFIG_GOOGLE_LANGUAGE="en"
    volumes:
      - ./nginx_logs:/var/log/nginx
      - ./php_logs:/var/log/php7
    restart: unless-stopped
```

## docker result
I'm slightly weary regarding the cursor being stuck at the end of this sequence when starting:
```
docker compose -f docker-compose-librey.yaml up 
[+] Running 1/0
 ✔ Container librex  Created                                                                                                                                                                                                  0.1s 
Attaching to librex
librex  | [PREPARE] docker/server/prepare.sh'
librex  | [PREPARE] docker/server/prepare.sh'
```
I would have expected some message that it's finished loading, but I've never used LibreY before, but docker ps indicates it's running OK, (I think):
```
docker ps
CONTAINER ID   IMAGE                  COMMAND                  CREATED          STATUS         PORTS                                       NAMES
28950dfbb9f5   librex/librex:latest   "/bin/sh -c docker/e…"   17 minutes ago   Up 8 minutes   0.0.0.0:8080->8080/tcp, :::8080->8080/tcp   librex

```

## search result
I get the search page, but when I search something, it loads an empty page (although same background color as the search page's theme). I've tried it in 3 different browsers (conkeror, firefox, chromium, the latter with no addons).

I assume it works for others, but not sure why it's not working for me.
